[project]
name = "memoria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = ["fastmcp>=2.0.0", "asyncpg>=0.27.0", "pytest>=7.1.0"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
